#!/usr/bin/env bash
# Downloads the libretro cores RetroGlass bundles, from the official libretro
# nightly buildbot (arm64-v8a), into app/src/main/jniLibs/arm64-v8a/.
# These are GPL binaries and are intentionally not committed to the repo.
set -euo pipefail

BASE="https://buildbot.libretro.com/nightly/android/latest/arm64-v8a"
DIR="$(cd "$(dirname "$0")/.." && pwd)/app/src/main/jniLibs/arm64-v8a"
mkdir -p "$DIR"

# buildbot core name  ->  output library name (lib<name>.so)
declare -A CORES=(
  [fceumm]=fceumm
  [snes9x]=snes9x
  [genesis_plus_gx]=genesis_plus_gx
  [pcsx_rearmed]=pcsx_rearmed
  [gambatte]=gambatte
  [mgba]=mgba
  [mupen64plus_next_gles3]=mupen64plus_next
  [mednafen_pce_fast]=mednafen_pce_fast
  [mednafen_ngp]=mednafen_ngp
  [flycast]=flycast
  [play]=play
  [handy]=handy
  [stella2023]=stella2023
  [prosystem]=prosystem
  [mednafen_wswan]=mednafen_wswan
  [mednafen_vb]=mednafen_vb
  [ppsspp]=ppsspp
  [melonds]=melonds
  [opera]=opera
  [mednafen_saturn]=mednafen_saturn
  [picodrive]=picodrive
  [gearcoleco]=gearcoleco
  [freeintv]=freeintv
  [vecx]=vecx
  [pokemini]=pokemini
  [atari800]=atari800
  [fbneo]=fbneo
)

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

for src in "${!CORES[@]}"; do
  out="${CORES[$src]}"
  echo "Fetching $src -> lib$out.so"
  curl -fsSL --retry 3 -o "$tmp/$src.zip" "$BASE/${src}_libretro_android.so.zip"
  unzip -oq "$tmp/$src.zip" -d "$tmp/$src"
  so="$(find "$tmp/$src" -name '*.so' | head -n1)"
  cp "$so" "$DIR/lib$out.so"
done

echo "Done. $(ls "$DIR" | wc -l) cores in $DIR"

# --- provenance -------------------------------------------------------------
# The buildbot serves "latest" and keeps no archive, so a version cannot be
# pinned in the usual sense. What can be done is record exactly what arrived, so
# a shipped APK is traceable to specific binaries and drift is detectable rather
# than silent. A core update has already changed GL behaviour between two runs
# of this script once. Also what makes the GPL written offer answerable: "which
# source produced this binary" needs an answer more precise than "latest".
MANIFEST="$(cd "$(dirname "$0")/.." && pwd)/scripts/core-manifest.txt"
{
  echo "# Cores bundled in this working tree. Regenerated by fetch_cores.sh."
  echo "# Compare with 'sha256sum -c' style diffing to spot an unintended core change."
  echo "# fetched-utc: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# source: $BASE"
  ( cd "$DIR" && sha256sum *.so 2>/dev/null | sort -k2 )
} > "$MANIFEST"
echo "Wrote $(basename "$MANIFEST")"
